name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Enable Corepack (Yarn)
        run: corepack enable

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true

      - name: Detect base URL
        shell: bash
        run: |
          REPO="${{ github.event.repository.name }}"
          OWNER="${{ github.repository_owner }}"
          if [[ "$REPO" == *.github.io ]]; then
            # User/Org pages: REPO is already like <owner>.github.io
            echo "BASE_URL=https://${REPO}" >> $GITHUB_ENV
            echo "BASE_PATH=/" >> $GITHUB_ENV
            echo "PUBLIC_BASE_URL=https://${REPO}" >> $GITHUB_ENV
          else
            # Project pages under <owner>.github.io/<repo>
            echo "BASE_URL=https://${OWNER}.github.io/${REPO}" >> $GITHUB_ENV
            echo "BASE_PATH=/${REPO}/" >> $GITHUB_ENV
            echo "PUBLIC_BASE_URL=https://${OWNER}.github.io/${REPO}" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile || yarn install

      - name: Build
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
